version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  express-server:
    build: ./
    container_name: express-server
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres-data:
